version: '2'
services:
  vhr-mysql:
    image: mysql:8.0.16
    volumes:
      - ~/.docker_data/volumes/vhr/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=vhr
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp
